### ISSUE TITLE
default date selection or goToday doesn't show current date selected

### ISSUE THREAD

**Issue by sairajkishore** [Mulham-Raee/Horizontal-Calendar#56]
when we are using defaultSelectedDate the calendar is not selecting current in stead it selects one day back to the current date.
also i gave 
 **horizontalCalendar.goToday(true);
 **horizontalCalendar.selectDate(new Date(),true);
so for above settings also it shows it is not selected current date.

### Expected Behavior / Goal
> ? It has to select by default current date.

### Actual Behavior
> ?

### Steps to Reproduce the Problem (sample code if possible)

  HorizontalCalendar horizontalCalendar = new HorizontalCalendar.Builder(this, R.id.calendarView)
                .startDate(startDate.getTime())
                .endDate(endDate.getTime())
                .datesNumberOnScreen(7)
                .dayNameFormat("EEE")
                .dayNumberFormat("dd")
                .monthFormat("MMM")
                .showDayName(true)
                .showMonthName(true)
                .selectedDateBackground(ContextCompat.getDrawable(this, R.drawable.ic_selectable_background))
                .defaultSelectedDate(defaultDate.getTime())
                .textColor(Color.GRAY, Color.rgb(15,26,42))
                .selectorColor(Color.rgb(15,26,42))
                .build();

Above is my constructor am using.

### Specifications

 > - Android Version:
 > - Horizontal-Calendar Version:

**Comment by sairajkishore** [comment]
There is a problem if  datesNumberOnScreen is 7 ,the current date selection goes wrong when we launch the calendar.

**Comment by Mulham-Raee** [comment]
@sairajkishore 

Your problem should be solved in version `1.2.2`, if not feel free to recomment on this issue.

Regards

**Comment by alliejc** [comment]
I am experiencing this issue with 1.3.2

**Comment by codeappointment** [comment]
The problem still exists on 1.3.4. after launching horizontalCalender it shows that current date  is selected but  horizontalCalendar.getSelectedDate() retuns date three days back.
