### ISSUE TITLE
goToday() and selectDate() selecting incorrect date

### ISSUE THREAD

**Issue by alliejc** [Mulham-Raee/Horizontal-Calendar#63]
### Expected Behavior / Goal
> I have placed a button in my toolbar that should return the horizontal calendar to today. 

### Actual Behavior
> Upon clicking the today button, the horizontal calendar will intermittently return to the wrong day.

### Steps to Reproduce the Problem

I have tried this 2 different ways:

Using selectDate()
```
  if(id == R.id.today_button) {
            Calendar today = Calendar.getInstance();
            if(mHorizontalCalendar != null){
                mHorizontalCalendar.selectDate(today, true);
            }
        }
```

Using goToday()
```
 if(id == R.id.today_button) {
            if(mHorizontalCalendar != null){
                mHorizontalCalendar.goToday(true);
            }
        }
```

When using selectDate(), the outcome is intermittently 1 day before (ie. today is Tuesday, it will switch between selecting Monday and Tuesday as today)

When using goToday(), the outcome is intermittently 1 day before, or 1 day after (ie. today is Tuesday, it will switch between selecting Monday, Tuesday, and Wednesday as today)

### Specifications

 > - Android Version: 6.0.1 and 8.1.0
 > - Horizontal-Calendar Version: 1.3.2

**Comment by alliejc** [comment]
@Mulham-Raee what does the timeline look like for releasing these changes? Thanks!

**Comment by Mulham-Raee** [comment]
@alliejc changes are live in version `1.3.4`

**Comment by srseibs** [comment]
I am having the same problem in 1.3.4 so I am not sure this is fixed.

**Comment by alliejc** [comment]
@srseibs  I am also still seeing the same problem

**Comment by KORuL** [comment]
@srseibs @Mulham-Raee  I am also still seeing the same problem

**Comment by muraee** [comment]
Issue fix was committed a while ago to this repository, but it is not available on jCenter yet. You can clone this repository and use it locally for now.

**Comment by KORuL** [comment]
I clone this repo!

```
        calendarHorizontal = HorizontalCalendar.Builder(this, R.id.calendarViewHorizontal)
            .range(startDate, endDate)
            .datesNumberOnScreen(8)   // Number of Dates cells shown on screen (Recommended 5)
            .configure()
            .formatTopText("EEE")       // default to "MMM".
            .formatMiddleText("dd")    // default to "dd".
            .formatBottomText("MMM''yy")    // default to "EEE".
            .sizeBottomText(10f)
            .sizeTopText(14f)
            .sizeMiddleText(21f)
            .textColor(
                ContextCompat.getColor(applicationContext, R.color.new_black_unsel),
                ContextCompat.getColor(applicationContext, R.color.new_black_sel)
            )    // Text color for none selected Dates, Text color for selected Date.
            .selectedDateBackground(getResourses().getDrawable(R.drawable.gradient_selected_calendar))  // Background Drawable of the selected date cell.
            .selectorColor(
                ContextCompat.getColor(
                    applicationContext,
                    R.color.new_calendar_selector_color
                )
            )
            .end()
            .defaultSelectedDate(Calendar.getInstance())
            .build()
```

if `datesNumberOnScreen(8) ` - selecting incorrect date
![image](https://user-images.githubusercontent.com/19871487/58745559-11617200-845b-11e9-8e29-3ec8884c6283.png)

My Issue #117
