### ISSUE TITLE
when ever i select a date it automatically goes to next date of the selected Date

### ISSUE THREAD

**Issue by HARMAN2231** [Mulham-Raee/Horizontal-Calendar#93]
Hello @Mulham-Raee,
I have an issue in Horizontal calendar, when ever i select a date it automatically goes to next date of selected Date..

![github](https://user-images.githubusercontent.com/36358646/44445716-bf540c00-a5ff-11e8-8bbe-c9ff362e9b7f.PNG)

In which actually it select the current date but it show the next date of that. 

Please let me know if there's any solution of this issue.

Thanks!

**Comment by Axtel209** [comment]
Same issue here.

**Comment by KarthikKompelli** [comment]
same issue

**Comment by KwangWookHa** [comment]
I have same issue... it's so fatal error.

**Comment by ranaprathap2** [comment]
same issue any fix ?

**Comment by muraee** [comment]
Issue fix was committed a while ago to this repository, but it is not available on jCenter yet. You can clone this repository and use it locally for now.

**Comment by LupinTheTh1rd** [comment]
> 
> 
> Issue fix was committed a while ago to this repository, but it is not available on jCenter yet. You can clone this repository and use it locally for now.

can you guide me how to do that? I am new to android studio, so am unaware how to use it locally.. 
or maybe make it available on jCenter altogether ;-;

**Comment by kiran-cmyk** [comment]
I have cloned the latest code and used it locally, But still facing the same issue. 
Issue seems to be only on mobile phones and not on tablets.

Please help me!!! Thanks...

**Comment by jcarlos79t** [comment]
TIENE YA SOLUCION????

**Comment by muhib27** [comment]
I have same issue
